In [119]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from statsmodels.tsa.stattools import adfuller

In [97]:
Ke_data = pd.read_excel('Ke_data.xlsx')
Ke_data.head(10)

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,KEN,SP.DYN.AMRT.MA,Data source: United Nations World Population P...,NaN
1,KEN,ST.INT.RCPT.CD,Compiled from data reported in the Internation...,NaN
2,KEN,SM.POP.NETM,Data source: United Nations World Population P...,NaN
3,KEN,SG.GEN.PARL.ZS,Situation for 1 January 2008 for directly elec...,NaN
4,KEN,ST.INT.TVLR.CD,Compiled from data reported in the Internation...,NaN
5,KEN,IT.CEL.SETS.P2,Kenya Posts and Telecommunications Corporation...,NaN
6,KEN,IT.NET.BBND,Kenya Posts and Telecommunications Corporation...,NaN
7,KEN,SP.DYN.LE00.MA.IN,Data source: United Nations World Population P...,NaN
8,KEN,SP.POP.GROW,Data source: United Nations World Population P...,NaN
9,KEN,ST.INT.XPND.CD,Compiled from data reported in the Internation...,NaN

In [98]:
KE_Country = pd.read_excel('KE_Country.xlsx')
KE_Country

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,KEN,Kenya,Kenya,Republic of Kenya,KE,Kenyan shilling,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Lower middle income,KE,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2009,"Malaria Indicator Survey, 2020","Integrated household survey (IHS), 2015/16",NaN,NaN,2013,2018,NaN

In [99]:
Ke_datas = pd.read_excel('Ke_datas.xlsx')
Ke_datas.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,year,Score
0,Kenya,KEN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,2000,1.800000
1,Kenya,KEN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,2000,0.500000
2,Kenya,KEN,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,2000,5.500000
3,Kenya,KEN,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,15.175694
4,Kenya,KEN,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,6.559743
5,Kenya,KEN,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,49.873398
6,Kenya,KEN,Account ownership at a financial institution o...,FX.OWN.TOTL.ZS,2000,NaN
7,Kenya,KEN,Account ownership at a financial institution o...,FX.OWN.TOTL.FE.ZS,2000,NaN
8,Kenya,KEN,Account ownership at a financial institution o...,FX.OWN.TOTL.MA.ZS,2000,NaN
9,Kenya,KEN,Account ownership at a financial institution o...,FX.OWN.TOTL.OL.ZS,2000,NaN

In [100]:
KE_FootNote = pd.read_excel('KE_FootNote.xlsx')
KE_FootNote.head()

  CountryCode         SeriesCode    Year   DESCRIPTION  Unnamed: 4
0         KEN     SE.PRM.NENR.MA  YR2009  UIS estimate         NaN
1         KEN     SE.PRM.NENR.FE  YR2009  UIS estimate         NaN
2         KEN  SE.PRM.NINT.FE.ZS  YR1999  UIS estimate         NaN
3         KEN  SE.PRM.NINT.MA.ZS  YR1999  UIS estimate         NaN
4         KEN     SE.PRM.NINT.ZS  YR1999  UIS estimate         NaN

In [101]:
KE_Time = pd.read_excel('KE_Series-Time.xlsx')
KE_Time

,SeriesCode,Year,DESCRIPTION,Unnamed: 3
0,SP.UWT.TFRT,YR1990,Averages for regions/groups are based on count...,NaN
1,SP.REG.DTHS.ZS,YR1990,Averages for regions/groups are based on count...,NaN
2,SH.FPL.SATM.ZS,YR1990,Averages for regions/groups are based on count...,NaN
3,SP.DYN.WFRT,YR1990,Averages for regions/groups are based on count...,NaN
4,SH.MED.CMHW.P3,YR1990,Averages for regions/groups are based on count...,NaN
...,...,...,...,...
144,SH.MLR.NETS.ZS,YR2019,Averages for regions/groups are based on most ...,NaN
145,SP.DYN.CONM.ZS,YR2019,Averages for regions/groups are based on most ...,NaN
146,SP.DYN.CONU.ZS,YR2019,Averages for regions/groups are based on most ...,NaN
147,SP.UWT.TFRT,YR2019,Averages for regions/groups are based on most ...,NaN
148,DT.DOD.PVLX.CD,YR2020,Present value calculations for these countries...,NaN

In [102]:
KE_Series = pd.read_excel('KE_Series.xlsx')

KE_Series.head()

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,...,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,AG.AGR.TRAC.NO,Environment: Agricultural production,"Agricultural machinery, tractors",NaN,Agricultural machinery refers to the number of...,NaN,Annual,NaN,NaN,Sum,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",A tractor provides the power and traction to m...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0,NaN
1,AG.CON.FERT.PT.ZS,Environment: Agricultural production,Fertilizer consumption (% of fertilizer produc...,NaN,Fertilizer consumption measures the quantity o...,NaN,Annual,NaN,The world and regional aggregate series do not...,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Fertilizer consumption measures the quantity o...,"Factors such as the green revolution, has led ...",NaN,NaN,NaN,CC BY-4.0,NaN
2,AG.CON.FERT.ZS,Environment: Agricultural production,Fertilizer consumption (kilograms per hectare ...,NaN,Fertilizer consumption measures the quantity o...,NaN,Annual,NaN,The world and regional aggregate series do not...,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Fertilizer consumption measures the quantity o...,"Factors such as the green revolution, has led ...",NaN,NaN,NaN,CC BY-4.0,NaN
3,AG.LND.AGRI.K2,Environment: Land use,Agricultural land (sq. km),NaN,Agricultural land refers to the share of land ...,NaN,Annual,NaN,Areas of former states are included in the suc...,Sum,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Agricultural land constitutes only a part of a...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0,NaN
4,AG.LND.AGRI.ZS,Environment: Land use,Agricultural land (% of land area),NaN,Agricultural land refers to the share of land ...,NaN,Annual,NaN,Areas of former states are included in the suc...,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Agriculture is still a major sector in many ec...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0,NaN

In [133]:
Economic_Indicators = ["Expense (current LCU)"]
Economic_data= Ke_datas[Ke_datas['Indicator Name'].isin(Economic_Indicators)]
Economic_data

,Country Name,Country Code,Indicator Name,Indicator Code,year,Score
397,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2000,NaN
1874,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2001,NaN
3351,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2002,NaN
4828,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2003,NaN
6305,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2004,NaN
7782,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2005,NaN
9259,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2006,NaN
10736,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2007,NaN
12213,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2008,NaN
13690,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2009,NaN
15167,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2010,NaN
16644,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2011,NaN
18121,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2012,NaN
19598,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2013,NaN
21075,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2014,1.233037e+12
22552,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2015,1.426091e+12
24029,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2016,1.685197e+12
25506,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2017,2.131751e+12
26983,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2018,2.207598e+12
28460,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2019,1.924521e+12
29937,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2020,2.142387e+12
31414,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2021,2.490483e+12
32891,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2022,NaN
34368,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,Unnamed: 67,NaN

In [263]:
Expense_data = pd.merge(Economic_data,KE_Series,right_on="Series Code",left_on="Indicator Code")
Expense_data

,Country Name,Country Code,Indicator Name_x,Indicator Code,year,Score,Series Code,Topic,Indicator Name_y,Short definition,...,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2000,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
1,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2001,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
2,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2002,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
3,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2003,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
4,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2004,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
5,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2005,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
6,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2006,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
7,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2007,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
8,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2008,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
9,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2009,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
10,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2010,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
11,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2011,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
12,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2012,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
13,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2013,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
14,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2014,1.233037e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
15,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2015,1.426091e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
16,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2016,1.685197e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
17,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2017,2.131751e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
18,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2018,2.207598e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
19,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2019,1.924521e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
20,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2020,2.142387e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
21,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2021,2.490483e+12,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
22,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,2022,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
23,Kenya,KEN,Expense (current LCU),GC.XPN.TOTL.CN,Unnamed: 67,NaN,GC.XPN.TOTL.CN,Public Sector: Government finance: Expense,Expense (current LCU),NaN,...,NaN,NaN,"International Monetary Fund, Government Financ...",The IMF's Government Finance Statistics Manual...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN

In [264]:
Expense_data.columns

Index(['Country Name', 'Country Code', 'Indicator Name_x', 'Indicator Code',
       'year', 'Score', 'Series Code', 'Topic', 'Indicator Name_y',
       'Short definition', 'Long definition', 'Unit of measure', 'Periodicity',
       'Base Period', 'Other notes', 'Aggregation method',
       'Limitations and exceptions', 'Notes from original source',
       'General comments', 'Source', 'Statistical concept and methodology',
       'Development relevance', 'Related source links', 'Other web links',
       'Related indicators', 'License Type', 'Unnamed: 20'],
      dtype='object')

In [265]:
necessary_columns = ['Country Name','Indicator Name_x','Indicator Code','year','Score','Topic','Long definition','Periodicity']

Expense_data = Expense_data[necessary_columns]

Expense_data

,Country Name,Indicator Name_x,Indicator Code,year,Score,Topic,Long definition,Periodicity
0,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2000,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
1,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2001,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2002,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
3,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2003,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
4,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2004,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
5,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2005,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
6,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2006,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
7,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2007,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
8,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2008,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
9,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2009,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
10,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2010,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
11,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2011,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
12,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2012,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
13,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2013,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
14,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2014,1.233037e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
15,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2015,1.426091e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
16,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2016,1.685197e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
17,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2017,2.131751e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
18,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2018,2.207598e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
19,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2019,1.924521e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
20,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2020,2.142387e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
21,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2021,2.490483e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
22,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2022,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
23,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,Unnamed: 67,NaN,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual

In [266]:
Expense_data['Score'].isna().sum()

16

In [267]:
Expense_data.isna().sum()

Country Name         0
Indicator Name_x     0
Indicator Code       0
year                 0
Score               16
Topic                0
Long definition      0
Periodicity          0
dtype: int64

In [268]:
Expense_data.dropna(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_29744\2279243034.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [269]:
# Convert 'year' column to datetime format
Expense_data['year'] = pd.to_datetime(Expense_data['year'])

# # Extract the year component
Expense_data['year'] = Expense_data['year'].dt.year

# # Set 'year' as the DataFrame's index
Expense_data.set_index('year', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_29744\4271851905.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\HP\AppData\Local\Temp\ipykernel_29744\4271851905.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [270]:
Expense_data = Expense_data.rename(columns={'Indicator Name_x':'Indicator Name'})
Expense_data

,Country Name,Indicator Name,Indicator Code,Score,Topic,Long definition,Periodicity
year,,,,,,,
2014,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,1.233037e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2015,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,1.426091e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2016,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,1.685197e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2017,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2.131751e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2018,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2.207598e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2019,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,1.924521e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2020,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2.142387e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual
2021,Kenya,Expense (current LCU),GC.XPN.TOTL.CN,2.490483e+12,Public Sector: Government finance: Expense,Expense is cash payments for operating activit...,Annual

In [271]:
Expense_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 2014 to 2021
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country Name     8 non-null      object
 1   Indicator Name   8 non-null      object
 2   Indicator Code   8 non-null      object
 3   Score            8 non-null      float64
 4   Topic            8 non-null      object
 5   Long definition  8 non-null      object
 6   Periodicity      8 non-null      object
dtypes: float64(1), object(6)
memory usage: 480.0+ bytes

In [282]:
# Convert Score column to numeric
Expense_data['Score'] = pd.to_numeric(Expense_data['Score'], errors='coerce')
# Drops missing values in Score Column
Expense_data.dropna(subset=['Score'], inplace=True)

# Checking th data type of Score column
Expense_data['Score'].values.dtype

dtype('float64')

In [283]:
# Plotting the score for the Expense data
selected_years = Expense_data.index.unique()
scores = Expense_data['Score'].apply(lambda x: '{:.2f}'.format(x))
year = Expense_data.index

# Create a trace for the line plot
trace = go.Scatter(x=year, y=scores, mode='lines', name='Score')

# Create the layout for the plot
layout = go.Layout(
    title="Expense allocated to Kenyan Government from (2014-2021)",
    xaxis=dict(title='Year'),
    yaxis=dict(title='Score'),
    legend=dict(font=dict(size=12), orientation='h', x=0, y=1.1)
)

# Create the figure and add the trace to it
fig = go.Figure(data=[trace], layout=layout)

# Show the plot
fig.show()

Acording to the graph above there has been an unprise in Expense; the amount of money the Kenyan government spends on operating activities in every sector of the economy combined. This was a good sign considering the rise in taxes over the years.

In [287]:
unique_years = Expense_data.index.unique()
adf_results = {}
threshold = 0.05  # Threshold for determining stationarity

for year in unique_years:
    # Fetch the time series data for the specific year
    year_data = Expense_data.loc[:, 'Score']

    # Check if the data is constant
    if year_data.std() == 0:
        adf_results[year] = 'Constant Data'
    else:
        # Perform the ADF test
        result = adfuller(year_data)
        p_value = result[1]

        # Determine stationarity based on the p-value
        if p_value < threshold:
            adf_results[year] = 'Stationary'
        else:
            adf_results[year] = 'Not Stationary'

# Print the stationarity results
for year, result in adf_results.items():
    print("Year:", year)
    print("Stationarity:", result)
    print()

Year: 2014
Stationarity: Stationary

Year: 2015
Stationarity: Stationary

Year: 2016
Stationarity: Stationary

Year: 2017
Stationarity: Stationary

Year: 2018
Stationarity: Stationary

Year: 2019
Stationarity: Stationary

Year: 2020
Stationarity: Stationary

Year: 2021
Stationarity: Stationary

Using the adullfer test and the visualization above using plotly library, it was confirmed that the time series data did not have any trends or seasonality hence it was suitable for predictive modelling without use of methods to remove non-stationarity.

In [276]:
# pip install plotly
# !pip install statsmodels